// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using ReactiveUI;
using ReactiveUI.Cocoa;
using VirtualSales.Core.ViewModels;

namespace VirtualSales.iOS
{
    public partial class MeetingSlidesViewController : ReactiveViewController, IViewFor<MeetingViewModel>
    {
        private MeetingViewModel _viewModel;

        public MeetingSlidesViewController(IntPtr handle) : base(handle)
        {
        }

        object IViewFor.ViewModel
        {
            get { return ViewModel; }
            set { ViewModel = (MeetingViewModel)value; }
        }

        public MeetingViewModel ViewModel
        {
            get { return _viewModel; }
            set { this.RaiseAndSetIfChanged(ref _viewModel, value); }
        }
    }
}