// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using ReactiveUI.Cocoa;

namespace VirtualSales.iOS
{
    public partial class ToolBoxViewController : ReactiveViewController
    {
        public ToolBoxViewController(IntPtr handle) : base(handle)
        {
        }
    }
}