// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using MonoTouch.UIKit;
using ReactiveUI;
using ReactiveUI.Cocoa;
using VirtualSales.Core.Models;
using VirtualSales.Core.ViewModels;

namespace VirtualSales.iOS
{
    public partial class UserInfoViewController : ReactiveViewController, IViewFor<PersonModel>
    {        
        private PersonModel _viewModel;

        public UserInfoViewController(IntPtr handle) : base(handle)
        {
            ViewModel = ((WhiteBrandAppDelegate)UIApplication.SharedApplication.Delegate).ViewModelLocator.SharedDataService.Person;
        }

        public override void ViewDidLoad()
        {
            this.Bind(ViewModel, vm => vm.FirstName, c => c.firstNameTextField.Text);
        }

        object IViewFor.ViewModel
        {
            get { return ViewModel; }
            set { ViewModel = (PersonModel)value; }
        }

        public PersonModel ViewModel
        {
            get { return _viewModel; }
            set { RaiseAndSetIfChanged(ref _viewModel, value); }
        }

    }
}